name: passport_to_the_north
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_login: ^5.0.0
  firebase_core: ^3.8.1
  firebase_data_connect: ^0.1.2+4
  firebase_auth: ^5.3.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.jpg
    - assets/festival.jpg
    - assets/hiking.jpg
    - assets/museum.jpg
    - assets/provincial_park.jpg
    - assets/tourist_attraction.jpg

  # If you want to add fonts, you can uncomment and modify the fonts section
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700